### ISSUE TITLE
Add Responsiveness to this Site

### ISSUE THREAD

**Issue by onnhyd** [sceary-expert/Codeforces-Problem-of-The-Day#1]
# This should look like this
![image](https://user-images.githubusercontent.com/84634405/187019508-5e64fb57-8323-4833-a42c-2089ee979473.png)

# But it looks like this
## Also it is not responsive on mobile or tablet devices.

![image](https://user-images.githubusercontent.com/84634405/187018398-181918b7-2ad3-4919-bbd9-6c7540cae18a.png)

![image](https://user-images.githubusercontent.com/84634405/187018391-9b51a71c-2dd6-4761-8858-e7c6d1508e57.png)
![image](https://user-images.githubusercontent.com/84634405/187018394-7a6a433f-097a-4738-badb-37731a991719.png)

**Comment by 0xPranjl** [comment]
can you assign it to me?

**Comment by onnhyd** [comment]
> can you assign it to me?

Done.

**Comment by 0xPranjl** [comment]
done check PR
