### ISSUE TITLE
Add a functional JavaScript code that generates a new Problem everyday.

### ISSUE THREAD

**Issue by onnhyd** [sceary-expert/Codeforces-Problem-of-The-Day#5]
This site should fetch a new problem everyday from codeforces and display that as Problem of The Day for 24 hours.

**Comment by Satyakoidala** [comment]
hi @sceary-expert ,

I would like to work on this issue. I think I could help you with this.

Could you assign this issue to me?

Thanks!

**Comment by onnhyd** [comment]
@Satyakoidala  make a pull request.

**Comment by Satyakoidala** [comment]
Hi @sceary-expert.

I have created a pull request, https://github.com/sceary-expert/Codeforces-Problem-of-The-Day/pull/7

Can you please check?

Thanks!
