### ISSUE TITLE
Fetch Problem according to selected rating

### ISSUE THREAD

**Issue by onnhyd** [sceary-expert/Codeforces-Problem-of-The-Day#8]
Make a sidebar where users can select any rating and make sure that the problem fetched by the API is of that rating.

**Comment by Satyakoidala** [comment]
Hi @sceary-expert, I would like to contribute to this issue. Can you please elaborate on your requirement a bit more?

**Comment by onnhyd** [comment]
> Hi @sceary-expert, I would like to contribute to this issue. Can you please elaborate on your requirement a bit more?
## Create a section where user can input the rating. See the image below for example
![image](https://user-images.githubusercontent.com/84634405/194757990-575c78e1-7dca-487f-85ee-7415986d211c.png)
![image](https://user-images.githubusercontent.com/84634405/194758035-52a22218-2ede-49ed-8bab-c63efe1fdbd1.png)

## After that store the input and fetch the problem of that rating 
Fox example if I select 1500 then I will see a Problem of 1500 rating.

**Comment by Satyakoidala** [comment]
hi @sceary-expert,

Understood! One more query, will the daily problem be updated if the user applies this difficulty rating filter?

Clarifying this, please assign this one to me.

Thanks!

**Comment by Satyakoidala** [comment]
hi @sceary-expert,

Can you also mention the minimum and maximum ratings for this rating form control? I found by research that 800 - 3500 is the range in Codeforces problems. Please do suggest if you have any form of input control in mind to implement this filter. If not, do I have the freedom to implement the filter with form input control of my choice?

Please clarify this too. Thanks!

**Comment by Satyakoidala** [comment]
hi @sceary-expert,

Can you also mention the minimum and maximum rating for the rating form control. I found by research that 800 - 3500 is the range. Do you have any form input control in mind to implement this filter? or Do I have the freedom to implement the filter with form input control of my choice

**Comment by onnhyd** [comment]
> hi @sceary-expert,
> 
> Can you also mention the minimum and maximum ratings for this rating form control? I found by research that 800 - 3500 is the range in Codeforces problems. Please do suggest if you have any form of input control in mind to implement this filter. If not, do I have the freedom to implement the filter with form input control of my choice?
> 
> Please clarify this too. Thanks!

Do as per your choice.

**Comment by Satyakoidala** [comment]
Hi @sceary-expert, can you assign this one to me?

**Comment by Satyakoidala** [comment]
Hi @sceary-expert,

I have the PR request ready. Could you please assign this one to me?

Thanks!

**Comment by Satyakoidala** [comment]
Hi @sceary-expert,

Here is the PR link. https://github.com/sceary-expert/Codeforces-Problem-of-The-Day/pull/11

Please verify it. Thanks!

**Comment by onnhyd** [comment]
> Hi @sceary-expert,
> 
> Here is the PR link. #11
> 
> Please verify it. Thanks!

Great job!

**Comment by Satyakoidala** [comment]
Hi @sceary-expert, Please accept this one as hacktober-accepted.
